const GE_FPS = 60;
const GE_VELOCITY_ITERATIONS = 10;
const GE_POSITION_ITERATIONS = 8;
const DATA_FRACTION = 1
const SIMULATED_LATENCY = 0;
const SIMULATED_LOSS = 0

module.exports = { GE_FPS, GE_VELOCITY_ITERATIONS, GE_POSITION_ITERATIONS, DATA_FRACTION, SIMULATED_LATENCY, SIMULATED_LOSS }